name: 'opensrp_mh'
version: '1.0.0'
config-version: 2

profile: 'opensrp_mh'  # define in ~/.dbt/profiles.yml

models:
  opensrp_mh:
    +materialized: view
    staging:
      +schema: stg
    intermediate:
      +schema: int
    marts:
      +schema: mart

seeds:
  opensrp_mh:
    score_map:
      +column_types:
        coding_code: text
        link_id: text
        questionnaire_match: text
