name: 'engage_analytics'
version: '1.0.0'
config-version: 2

profile: 'engage_analytics'

models:
  engage_analytics:
    +materialized: view
    staging:
      +schema: engage_analytics_stg
    intermediate:
      +schema: engage_analytics_int
    marts:
      +schema: engage_analytics_mart

seeds:
  engage_analytics:
    +schema: engage_analytics_stg
