engage_analytics:
  target: prod
  outputs:
    prod:
      type: postgres
      host: "{{ env_var('DBT_HOST') }}"
      port: "{{ env_var('DBT_PORT', '5432') | int }}"
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      dbname: "{{ env_var('DBT_DATABASE') }}"
      schema: "{{ env_var('DBT_SCHEMA', 'engage_analytics') }}"
      threads: 4
      keepalives_idle: 0
      connect_timeout: 30
      sslmode: "{{ env_var('DBT_SSLMODE', 'prefer') }}"
