engage_analytics:
  target: prod
  outputs:
    prod:
      type: postgres
      host: localhost
      port: 5432
      user: "postgres"
      password: "knox48"
      dbname: "airbyte"
      schema: "engage_analytics"
      threads: 4
      keepalives_idle: 0
      connect_timeout: 30
      sslmode: "{{ env_var('DBT_SSLMODE', 'prefer') }}"
