-- ABOUTME: Calculates PHQ-9 and GAD-7 scores across all 4 sessions
-- ABOUTME: Enables tracking symptom change over treatment (indicator #22)

{{ config(materialized='view') }}

-- PHQ-9 Session 1
with phq9_s1 as (
    select
        subject_patient_id,
        practitioner_organization_id as organization_id,
        qr_id,
        1 as session_number,
        'PHQ-9' as assessment_type,
        (coalesce(case when common_mental_health_symptoms_little_interest_or_pleasure_in__2 like '0 -%' or common_mental_health_symptoms_little_interest_or_pleasure_in__2 = 'Not at all' then 0 when common_mental_health_symptoms_little_interest_or_pleasure_in__2 like '1 -%' or common_mental_health_symptoms_little_interest_or_pleasure_in__2 = 'Several days' then 1 when common_mental_health_symptoms_little_interest_or_pleasure_in__2 like '2 -%' or common_mental_health_symptoms_little_interest_or_pleasure_in__2 = 'More than half the days' then 2 when common_mental_health_symptoms_little_interest_or_pleasure_in__2 like '3 -%' or common_mental_health_symptoms_little_interest_or_pleasure_in__2 = 'Nearly every day' then 3 else null end, 0) +
         coalesce(case when common_mental_health_symptoms_feeling_down_depressed_or_hopel_2 like '0 -%' or common_mental_health_symptoms_feeling_down_depressed_or_hopel_2 = 'Not at all' then 0 when common_mental_health_symptoms_feeling_down_depressed_or_hopel_2 like '1 -%' or common_mental_health_symptoms_feeling_down_depressed_or_hopel_2 = 'Several days' then 1 when common_mental_health_symptoms_feeling_down_depressed_or_hopel_2 like '2 -%' or common_mental_health_symptoms_feeling_down_depressed_or_hopel_2 = 'More than half the days' then 2 when common_mental_health_symptoms_feeling_down_depressed_or_hopel_2 like '3 -%' or common_mental_health_symptoms_feeling_down_depressed_or_hopel_2 = 'Nearly every day' then 3 else null end, 0) +
         coalesce(case when common_mental_health_symptoms_trouble_falling_or_staying_asle_2 like '0 -%' or common_mental_health_symptoms_trouble_falling_or_staying_asle_2 = 'Not at all' then 0 when common_mental_health_symptoms_trouble_falling_or_staying_asle_2 like '1 -%' or common_mental_health_symptoms_trouble_falling_or_staying_asle_2 = 'Several days' then 1 when common_mental_health_symptoms_trouble_falling_or_staying_asle_2 like '2 -%' or common_mental_health_symptoms_trouble_falling_or_staying_asle_2 = 'More than half the days' then 2 when common_mental_health_symptoms_trouble_falling_or_staying_asle_2 like '3 -%' or common_mental_health_symptoms_trouble_falling_or_staying_asle_2 = 'Nearly every day' then 3 else null end, 0) +
         coalesce(case when common_mental_health_symptoms_feeling_tired_or_having_little__2 like '0 -%' or common_mental_health_symptoms_feeling_tired_or_having_little__2 = 'Not at all' then 0 when common_mental_health_symptoms_feeling_tired_or_having_little__2 like '1 -%' or common_mental_health_symptoms_feeling_tired_or_having_little__2 = 'Several days' then 1 when common_mental_health_symptoms_feeling_tired_or_having_little__2 like '2 -%' or common_mental_health_symptoms_feeling_tired_or_having_little__2 = 'More than half the days' then 2 when common_mental_health_symptoms_feeling_tired_or_having_little__2 like '3 -%' or common_mental_health_symptoms_feeling_tired_or_having_little__2 = 'Nearly every day' then 3 else null end, 0) +
         coalesce(case when common_mental_health_symptoms_poor_appetite_or_overeating_2 like '0 -%' or common_mental_health_symptoms_poor_appetite_or_overeating_2 = 'Not at all' then 0 when common_mental_health_symptoms_poor_appetite_or_overeating_2 like '1 -%' or common_mental_health_symptoms_poor_appetite_or_overeating_2 = 'Several days' then 1 when common_mental_health_symptoms_poor_appetite_or_overeating_2 like '2 -%' or common_mental_health_symptoms_poor_appetite_or_overeating_2 = 'More than half the days' then 2 when common_mental_health_symptoms_poor_appetite_or_overeating_2 like '3 -%' or common_mental_health_symptoms_poor_appetite_or_overeating_2 = 'Nearly every day' then 3 else null end, 0) +
         coalesce(case when common_mental_health_symptoms_feeling_bad_about_yourself_or_t_2 like '0 -%' or common_mental_health_symptoms_feeling_bad_about_yourself_or_t_2 = 'Not at all' then 0 when common_mental_health_symptoms_feeling_bad_about_yourself_or_t_2 like '1 -%' or common_mental_health_symptoms_feeling_bad_about_yourself_or_t_2 = 'Several days' then 1 when common_mental_health_symptoms_feeling_bad_about_yourself_or_t_2 like '2 -%' or common_mental_health_symptoms_feeling_bad_about_yourself_or_t_2 = 'More than half the days' then 2 when common_mental_health_symptoms_feeling_bad_about_yourself_or_t_2 like '3 -%' or common_mental_health_symptoms_feeling_bad_about_yourself_or_t_2 = 'Nearly every day' then 3 else null end, 0) +
         coalesce(case when common_mental_health_symptoms_trouble_concentrating_on_things_2 like '0 -%' or common_mental_health_symptoms_trouble_concentrating_on_things_2 = 'Not at all' then 0 when common_mental_health_symptoms_trouble_concentrating_on_things_2 like '1 -%' or common_mental_health_symptoms_trouble_concentrating_on_things_2 = 'Several days' then 1 when common_mental_health_symptoms_trouble_concentrating_on_things_2 like '2 -%' or common_mental_health_symptoms_trouble_concentrating_on_things_2 = 'More than half the days' then 2 when common_mental_health_symptoms_trouble_concentrating_on_things_2 like '3 -%' or common_mental_health_symptoms_trouble_concentrating_on_things_2 = 'Nearly every day' then 3 else null end, 0) +
         coalesce(case when common_mental_health_symptoms_moving_or_speaking_so_slowly_th_2 like '0 -%' or common_mental_health_symptoms_moving_or_speaking_so_slowly_th_2 = 'Not at all' then 0 when common_mental_health_symptoms_moving_or_speaking_so_slowly_th_2 like '1 -%' or common_mental_health_symptoms_moving_or_speaking_so_slowly_th_2 = 'Several days' then 1 when common_mental_health_symptoms_moving_or_speaking_so_slowly_th_2 like '2 -%' or common_mental_health_symptoms_moving_or_speaking_so_slowly_th_2 = 'More than half the days' then 2 when common_mental_health_symptoms_moving_or_speaking_so_slowly_th_2 like '3 -%' or common_mental_health_symptoms_moving_or_speaking_so_slowly_th_2 = 'Nearly every day' then 3 else null end, 0) +
         coalesce(case when common_mental_health_symptoms_thoughts_that_you_would_be_bett_2 like '0 -%' or common_mental_health_symptoms_thoughts_that_you_would_be_bett_2 = 'Not at all' then 0 when common_mental_health_symptoms_thoughts_that_you_would_be_bett_2 like '1 -%' or common_mental_health_symptoms_thoughts_that_you_would_be_bett_2 = 'Several days' then 1 when common_mental_health_symptoms_thoughts_that_you_would_be_bett_2 like '2 -%' or common_mental_health_symptoms_thoughts_that_you_would_be_bett_2 = 'More than half the days' then 2 when common_mental_health_symptoms_thoughts_that_you_would_be_bett_2 like '3 -%' or common_mental_health_symptoms_thoughts_that_you_would_be_bett_2 = 'Nearly every day' then 3 else null end, 0)) as total_score
    from {{ ref('qr_phq_9_s1') }}
    where subject_patient_id is not null
),

-- PHQ-9 Session 2 (suffix _3)
phq9_s2 as (
    select
        subject_patient_id,
        practitioner_organization_id as organization_id,
        qr_id,
        2 as session_number,
        'PHQ-9' as assessment_type,
        (coalesce(case when common_mental_health_symptoms_little_interest_or_pleasure_in__3 like '0 -%' or common_mental_health_symptoms_little_interest_or_pleasure_in__3 = 'Not at all' then 0 when common_mental_health_symptoms_little_interest_or_pleasure_in__3 like '1 -%' or common_mental_health_symptoms_little_interest_or_pleasure_in__3 = 'Several days' then 1 when common_mental_health_symptoms_little_interest_or_pleasure_in__3 like '2 -%' or common_mental_health_symptoms_little_interest_or_pleasure_in__3 = 'More than half the days' then 2 when common_mental_health_symptoms_little_interest_or_pleasure_in__3 like '3 -%' or common_mental_health_symptoms_little_interest_or_pleasure_in__3 = 'Nearly every day' then 3 else null end, 0) +
         coalesce(case when common_mental_health_symptoms_feeling_down_depressed_or_hopel_3 like '0 -%' or common_mental_health_symptoms_feeling_down_depressed_or_hopel_3 = 'Not at all' then 0 when common_mental_health_symptoms_feeling_down_depressed_or_hopel_3 like '1 -%' or common_mental_health_symptoms_feeling_down_depressed_or_hopel_3 = 'Several days' then 1 when common_mental_health_symptoms_feeling_down_depressed_or_hopel_3 like '2 -%' or common_mental_health_symptoms_feeling_down_depressed_or_hopel_3 = 'More than half the days' then 2 when common_mental_health_symptoms_feeling_down_depressed_or_hopel_3 like '3 -%' or common_mental_health_symptoms_feeling_down_depressed_or_hopel_3 = 'Nearly every day' then 3 else null end, 0) +
         coalesce(case when common_mental_health_symptoms_trouble_falling_or_staying_asle_3 like '0 -%' or common_mental_health_symptoms_trouble_falling_or_staying_asle_3 = 'Not at all' then 0 when common_mental_health_symptoms_trouble_falling_or_staying_asle_3 like '1 -%' or common_mental_health_symptoms_trouble_falling_or_staying_asle_3 = 'Several days' then 1 when common_mental_health_symptoms_trouble_falling_or_staying_asle_3 like '2 -%' or common_mental_health_symptoms_trouble_falling_or_staying_asle_3 = 'More than half the days' then 2 when common_mental_health_symptoms_trouble_falling_or_staying_asle_3 like '3 -%' or common_mental_health_symptoms_trouble_falling_or_staying_asle_3 = 'Nearly every day' then 3 else null end, 0) +
         coalesce(case when common_mental_health_symptoms_feeling_tired_or_having_little__3 like '0 -%' or common_mental_health_symptoms_feeling_tired_or_having_little__3 = 'Not at all' then 0 when common_mental_health_symptoms_feeling_tired_or_having_little__3 like '1 -%' or common_mental_health_symptoms_feeling_tired_or_having_little__3 = 'Several days' then 1 when common_mental_health_symptoms_feeling_tired_or_having_little__3 like '2 -%' or common_mental_health_symptoms_feeling_tired_or_having_little__3 = 'More than half the days' then 2 when common_mental_health_symptoms_feeling_tired_or_having_little__3 like '3 -%' or common_mental_health_symptoms_feeling_tired_or_having_little__3 = 'Nearly every day' then 3 else null end, 0) +
         coalesce(case when common_mental_health_symptoms_poor_appetite_or_overeating_3 like '0 -%' or common_mental_health_symptoms_poor_appetite_or_overeating_3 = 'Not at all' then 0 when common_mental_health_symptoms_poor_appetite_or_overeating_3 like '1 -%' or common_mental_health_symptoms_poor_appetite_or_overeating_3 = 'Several days' then 1 when common_mental_health_symptoms_poor_appetite_or_overeating_3 like '2 -%' or common_mental_health_symptoms_poor_appetite_or_overeating_3 = 'More than half the days' then 2 when common_mental_health_symptoms_poor_appetite_or_overeating_3 like '3 -%' or common_mental_health_symptoms_poor_appetite_or_overeating_3 = 'Nearly every day' then 3 else null end, 0) +
         coalesce(case when common_mental_health_symptoms_feeling_bad_about_yourself_or_t_3 like '0 -%' or common_mental_health_symptoms_feeling_bad_about_yourself_or_t_3 = 'Not at all' then 0 when common_mental_health_symptoms_feeling_bad_about_yourself_or_t_3 like '1 -%' or common_mental_health_symptoms_feeling_bad_about_yourself_or_t_3 = 'Several days' then 1 when common_mental_health_symptoms_feeling_bad_about_yourself_or_t_3 like '2 -%' or common_mental_health_symptoms_feeling_bad_about_yourself_or_t_3 = 'More than half the days' then 2 when common_mental_health_symptoms_feeling_bad_about_yourself_or_t_3 like '3 -%' or common_mental_health_symptoms_feeling_bad_about_yourself_or_t_3 = 'Nearly every day' then 3 else null end, 0) +
         coalesce(case when common_mental_health_symptoms_trouble_concentrating_on_things_3 like '0 -%' or common_mental_health_symptoms_trouble_concentrating_on_things_3 = 'Not at all' then 0 when common_mental_health_symptoms_trouble_concentrating_on_things_3 like '1 -%' or common_mental_health_symptoms_trouble_concentrating_on_things_3 = 'Several days' then 1 when common_mental_health_symptoms_trouble_concentrating_on_things_3 like '2 -%' or common_mental_health_symptoms_trouble_concentrating_on_things_3 = 'More than half the days' then 2 when common_mental_health_symptoms_trouble_concentrating_on_things_3 like '3 -%' or common_mental_health_symptoms_trouble_concentrating_on_things_3 = 'Nearly every day' then 3 else null end, 0) +
         coalesce(case when common_mental_health_symptoms_moving_or_speaking_so_slowly_th_3 like '0 -%' or common_mental_health_symptoms_moving_or_speaking_so_slowly_th_3 = 'Not at all' then 0 when common_mental_health_symptoms_moving_or_speaking_so_slowly_th_3 like '1 -%' or common_mental_health_symptoms_moving_or_speaking_so_slowly_th_3 = 'Several days' then 1 when common_mental_health_symptoms_moving_or_speaking_so_slowly_th_3 like '2 -%' or common_mental_health_symptoms_moving_or_speaking_so_slowly_th_3 = 'More than half the days' then 2 when common_mental_health_symptoms_moving_or_speaking_so_slowly_th_3 like '3 -%' or common_mental_health_symptoms_moving_or_speaking_so_slowly_th_3 = 'Nearly every day' then 3 else null end, 0) +
         coalesce(case when common_mental_health_symptoms_thoughts_that_you_would_be_bett_3 like '0 -%' or common_mental_health_symptoms_thoughts_that_you_would_be_bett_3 = 'Not at all' then 0 when common_mental_health_symptoms_thoughts_that_you_would_be_bett_3 like '1 -%' or common_mental_health_symptoms_thoughts_that_you_would_be_bett_3 = 'Several days' then 1 when common_mental_health_symptoms_thoughts_that_you_would_be_bett_3 like '2 -%' or common_mental_health_symptoms_thoughts_that_you_would_be_bett_3 = 'More than half the days' then 2 when common_mental_health_symptoms_thoughts_that_you_would_be_bett_3 like '3 -%' or common_mental_health_symptoms_thoughts_that_you_would_be_bett_3 = 'Nearly every day' then 3 else null end, 0)) as total_score
    from {{ ref('qr_phq_9_s2') }}
    where subject_patient_id is not null
),

-- PHQ-9 Session 3 (suffix _4)
phq9_s3 as (
    select
        subject_patient_id,
        practitioner_organization_id as organization_id,
        qr_id,
        3 as session_number,
        'PHQ-9' as assessment_type,
        (coalesce(case when common_mental_health_symptoms_little_interest_or_pleasure_in__4 like '0 -%' or common_mental_health_symptoms_little_interest_or_pleasure_in__4 = 'Not at all' then 0 when common_mental_health_symptoms_little_interest_or_pleasure_in__4 like '1 -%' or common_mental_health_symptoms_little_interest_or_pleasure_in__4 = 'Several days' then 1 when common_mental_health_symptoms_little_interest_or_pleasure_in__4 like '2 -%' or common_mental_health_symptoms_little_interest_or_pleasure_in__4 = 'More than half the days' then 2 when common_mental_health_symptoms_little_interest_or_pleasure_in__4 like '3 -%' or common_mental_health_symptoms_little_interest_or_pleasure_in__4 = 'Nearly every day' then 3 else null end, 0) +
         coalesce(case when common_mental_health_symptoms_feeling_down_depressed_or_hopel_4 like '0 -%' or common_mental_health_symptoms_feeling_down_depressed_or_hopel_4 = 'Not at all' then 0 when common_mental_health_symptoms_feeling_down_depressed_or_hopel_4 like '1 -%' or common_mental_health_symptoms_feeling_down_depressed_or_hopel_4 = 'Several days' then 1 when common_mental_health_symptoms_feeling_down_depressed_or_hopel_4 like '2 -%' or common_mental_health_symptoms_feeling_down_depressed_or_hopel_4 = 'More than half the days' then 2 when common_mental_health_symptoms_feeling_down_depressed_or_hopel_4 like '3 -%' or common_mental_health_symptoms_feeling_down_depressed_or_hopel_4 = 'Nearly every day' then 3 else null end, 0) +
         coalesce(case when common_mental_health_symptoms_trouble_falling_or_staying_asle_4 like '0 -%' or common_mental_health_symptoms_trouble_falling_or_staying_asle_4 = 'Not at all' then 0 when common_mental_health_symptoms_trouble_falling_or_staying_asle_4 like '1 -%' or common_mental_health_symptoms_trouble_falling_or_staying_asle_4 = 'Several days' then 1 when common_mental_health_symptoms_trouble_falling_or_staying_asle_4 like '2 -%' or common_mental_health_symptoms_trouble_falling_or_staying_asle_4 = 'More than half the days' then 2 when common_mental_health_symptoms_trouble_falling_or_staying_asle_4 like '3 -%' or common_mental_health_symptoms_trouble_falling_or_staying_asle_4 = 'Nearly every day' then 3 else null end, 0) +
         coalesce(case when common_mental_health_symptoms_feeling_tired_or_having_little__4 like '0 -%' or common_mental_health_symptoms_feeling_tired_or_having_little__4 = 'Not at all' then 0 when common_mental_health_symptoms_feeling_tired_or_having_little__4 like '1 -%' or common_mental_health_symptoms_feeling_tired_or_having_little__4 = 'Several days' then 1 when common_mental_health_symptoms_feeling_tired_or_having_little__4 like '2 -%' or common_mental_health_symptoms_feeling_tired_or_having_little__4 = 'More than half the days' then 2 when common_mental_health_symptoms_feeling_tired_or_having_little__4 like '3 -%' or common_mental_health_symptoms_feeling_tired_or_having_little__4 = 'Nearly every day' then 3 else null end, 0) +
         coalesce(case when common_mental_health_symptoms_poor_appetite_or_overeating_4 like '0 -%' or common_mental_health_symptoms_poor_appetite_or_overeating_4 = 'Not at all' then 0 when common_mental_health_symptoms_poor_appetite_or_overeating_4 like '1 -%' or common_mental_health_symptoms_poor_appetite_or_overeating_4 = 'Several days' then 1 when common_mental_health_symptoms_poor_appetite_or_overeating_4 like '2 -%' or common_mental_health_symptoms_poor_appetite_or_overeating_4 = 'More than half the days' then 2 when common_mental_health_symptoms_poor_appetite_or_overeating_4 like '3 -%' or common_mental_health_symptoms_poor_appetite_or_overeating_4 = 'Nearly every day' then 3 else null end, 0) +
         coalesce(case when common_mental_health_symptoms_feeling_bad_about_yourself_or_t_4 like '0 -%' or common_mental_health_symptoms_feeling_bad_about_yourself_or_t_4 = 'Not at all' then 0 when common_mental_health_symptoms_feeling_bad_about_yourself_or_t_4 like '1 -%' or common_mental_health_symptoms_feeling_bad_about_yourself_or_t_4 = 'Several days' then 1 when common_mental_health_symptoms_feeling_bad_about_yourself_or_t_4 like '2 -%' or common_mental_health_symptoms_feeling_bad_about_yourself_or_t_4 = 'More than half the days' then 2 when common_mental_health_symptoms_feeling_bad_about_yourself_or_t_4 like '3 -%' or common_mental_health_symptoms_feeling_bad_about_yourself_or_t_4 = 'Nearly every day' then 3 else null end, 0) +
         coalesce(case when common_mental_health_symptoms_trouble_concentrating_on_things_4 like '0 -%' or common_mental_health_symptoms_trouble_concentrating_on_things_4 = 'Not at all' then 0 when common_mental_health_symptoms_trouble_concentrating_on_things_4 like '1 -%' or common_mental_health_symptoms_trouble_concentrating_on_things_4 = 'Several days' then 1 when common_mental_health_symptoms_trouble_concentrating_on_things_4 like '2 -%' or common_mental_health_symptoms_trouble_concentrating_on_things_4 = 'More than half the days' then 2 when common_mental_health_symptoms_trouble_concentrating_on_things_4 like '3 -%' or common_mental_health_symptoms_trouble_concentrating_on_things_4 = 'Nearly every day' then 3 else null end, 0) +
         coalesce(case when common_mental_health_symptoms_moving_or_speaking_so_slowly_th_4 like '0 -%' or common_mental_health_symptoms_moving_or_speaking_so_slowly_th_4 = 'Not at all' then 0 when common_mental_health_symptoms_moving_or_speaking_so_slowly_th_4 like '1 -%' or common_mental_health_symptoms_moving_or_speaking_so_slowly_th_4 = 'Several days' then 1 when common_mental_health_symptoms_moving_or_speaking_so_slowly_th_4 like '2 -%' or common_mental_health_symptoms_moving_or_speaking_so_slowly_th_4 = 'More than half the days' then 2 when common_mental_health_symptoms_moving_or_speaking_so_slowly_th_4 like '3 -%' or common_mental_health_symptoms_moving_or_speaking_so_slowly_th_4 = 'Nearly every day' then 3 else null end, 0) +
         coalesce(case when common_mental_health_symptoms_thoughts_that_you_would_be_bett_4 like '0 -%' or common_mental_health_symptoms_thoughts_that_you_would_be_bett_4 = 'Not at all' then 0 when common_mental_health_symptoms_thoughts_that_you_would_be_bett_4 like '1 -%' or common_mental_health_symptoms_thoughts_that_you_would_be_bett_4 = 'Several days' then 1 when common_mental_health_symptoms_thoughts_that_you_would_be_bett_4 like '2 -%' or common_mental_health_symptoms_thoughts_that_you_would_be_bett_4 = 'More than half the days' then 2 when common_mental_health_symptoms_thoughts_that_you_would_be_bett_4 like '3 -%' or common_mental_health_symptoms_thoughts_that_you_would_be_bett_4 = 'Nearly every day' then 3 else null end, 0)) as total_score
    from {{ ref('qr_phq_9_s3') }}
    where subject_patient_id is not null
),

-- PHQ-9 Session 4 (suffix _5)
phq9_s4 as (
    select
        subject_patient_id,
        practitioner_organization_id as organization_id,
        qr_id,
        4 as session_number,
        'PHQ-9' as assessment_type,
        (coalesce(case when common_mental_health_symptoms_little_interest_or_pleasure_in__5 like '0 -%' or common_mental_health_symptoms_little_interest_or_pleasure_in__5 = 'Not at all' then 0 when common_mental_health_symptoms_little_interest_or_pleasure_in__5 like '1 -%' or common_mental_health_symptoms_little_interest_or_pleasure_in__5 = 'Several days' then 1 when common_mental_health_symptoms_little_interest_or_pleasure_in__5 like '2 -%' or common_mental_health_symptoms_little_interest_or_pleasure_in__5 = 'More than half the days' then 2 when common_mental_health_symptoms_little_interest_or_pleasure_in__5 like '3 -%' or common_mental_health_symptoms_little_interest_or_pleasure_in__5 = 'Nearly every day' then 3 else null end, 0) +
         coalesce(case when common_mental_health_symptoms_feeling_down_depressed_or_hopel_5 like '0 -%' or common_mental_health_symptoms_feeling_down_depressed_or_hopel_5 = 'Not at all' then 0 when common_mental_health_symptoms_feeling_down_depressed_or_hopel_5 like '1 -%' or common_mental_health_symptoms_feeling_down_depressed_or_hopel_5 = 'Several days' then 1 when common_mental_health_symptoms_feeling_down_depressed_or_hopel_5 like '2 -%' or common_mental_health_symptoms_feeling_down_depressed_or_hopel_5 = 'More than half the days' then 2 when common_mental_health_symptoms_feeling_down_depressed_or_hopel_5 like '3 -%' or common_mental_health_symptoms_feeling_down_depressed_or_hopel_5 = 'Nearly every day' then 3 else null end, 0) +
         coalesce(case when common_mental_health_symptoms_trouble_falling_or_staying_asle_5 like '0 -%' or common_mental_health_symptoms_trouble_falling_or_staying_asle_5 = 'Not at all' then 0 when common_mental_health_symptoms_trouble_falling_or_staying_asle_5 like '1 -%' or common_mental_health_symptoms_trouble_falling_or_staying_asle_5 = 'Several days' then 1 when common_mental_health_symptoms_trouble_falling_or_staying_asle_5 like '2 -%' or common_mental_health_symptoms_trouble_falling_or_staying_asle_5 = 'More than half the days' then 2 when common_mental_health_symptoms_trouble_falling_or_staying_asle_5 like '3 -%' or common_mental_health_symptoms_trouble_falling_or_staying_asle_5 = 'Nearly every day' then 3 else null end, 0) +
         coalesce(case when common_mental_health_symptoms_feeling_tired_or_having_little__5 like '0 -%' or common_mental_health_symptoms_feeling_tired_or_having_little__5 = 'Not at all' then 0 when common_mental_health_symptoms_feeling_tired_or_having_little__5 like '1 -%' or common_mental_health_symptoms_feeling_tired_or_having_little__5 = 'Several days' then 1 when common_mental_health_symptoms_feeling_tired_or_having_little__5 like '2 -%' or common_mental_health_symptoms_feeling_tired_or_having_little__5 = 'More than half the days' then 2 when common_mental_health_symptoms_feeling_tired_or_having_little__5 like '3 -%' or common_mental_health_symptoms_feeling_tired_or_having_little__5 = 'Nearly every day' then 3 else null end, 0) +
         coalesce(case when common_mental_health_symptoms_poor_appetite_or_overeating_5 like '0 -%' or common_mental_health_symptoms_poor_appetite_or_overeating_5 = 'Not at all' then 0 when common_mental_health_symptoms_poor_appetite_or_overeating_5 like '1 -%' or common_mental_health_symptoms_poor_appetite_or_overeating_5 = 'Several days' then 1 when common_mental_health_symptoms_poor_appetite_or_overeating_5 like '2 -%' or common_mental_health_symptoms_poor_appetite_or_overeating_5 = 'More than half the days' then 2 when common_mental_health_symptoms_poor_appetite_or_overeating_5 like '3 -%' or common_mental_health_symptoms_poor_appetite_or_overeating_5 = 'Nearly every day' then 3 else null end, 0) +
         coalesce(case when common_mental_health_symptoms_feeling_bad_about_yourself_or_t_5 like '0 -%' or common_mental_health_symptoms_feeling_bad_about_yourself_or_t_5 = 'Not at all' then 0 when common_mental_health_symptoms_feeling_bad_about_yourself_or_t_5 like '1 -%' or common_mental_health_symptoms_feeling_bad_about_yourself_or_t_5 = 'Several days' then 1 when common_mental_health_symptoms_feeling_bad_about_yourself_or_t_5 like '2 -%' or common_mental_health_symptoms_feeling_bad_about_yourself_or_t_5 = 'More than half the days' then 2 when common_mental_health_symptoms_feeling_bad_about_yourself_or_t_5 like '3 -%' or common_mental_health_symptoms_feeling_bad_about_yourself_or_t_5 = 'Nearly every day' then 3 else null end, 0) +
         coalesce(case when common_mental_health_symptoms_trouble_concentrating_on_things_5 like '0 -%' or common_mental_health_symptoms_trouble_concentrating_on_things_5 = 'Not at all' then 0 when common_mental_health_symptoms_trouble_concentrating_on_things_5 like '1 -%' or common_mental_health_symptoms_trouble_concentrating_on_things_5 = 'Several days' then 1 when common_mental_health_symptoms_trouble_concentrating_on_things_5 like '2 -%' or common_mental_health_symptoms_trouble_concentrating_on_things_5 = 'More than half the days' then 2 when common_mental_health_symptoms_trouble_concentrating_on_things_5 like '3 -%' or common_mental_health_symptoms_trouble_concentrating_on_things_5 = 'Nearly every day' then 3 else null end, 0) +
         coalesce(case when common_mental_health_symptoms_moving_or_speaking_so_slowly_th_5 like '0 -%' or common_mental_health_symptoms_moving_or_speaking_so_slowly_th_5 = 'Not at all' then 0 when common_mental_health_symptoms_moving_or_speaking_so_slowly_th_5 like '1 -%' or common_mental_health_symptoms_moving_or_speaking_so_slowly_th_5 = 'Several days' then 1 when common_mental_health_symptoms_moving_or_speaking_so_slowly_th_5 like '2 -%' or common_mental_health_symptoms_moving_or_speaking_so_slowly_th_5 = 'More than half the days' then 2 when common_mental_health_symptoms_moving_or_speaking_so_slowly_th_5 like '3 -%' or common_mental_health_symptoms_moving_or_speaking_so_slowly_th_5 = 'Nearly every day' then 3 else null end, 0) +
         coalesce(case when common_mental_health_symptoms_thoughts_that_you_would_be_bett_5 like '0 -%' or common_mental_health_symptoms_thoughts_that_you_would_be_bett_5 = 'Not at all' then 0 when common_mental_health_symptoms_thoughts_that_you_would_be_bett_5 like '1 -%' or common_mental_health_symptoms_thoughts_that_you_would_be_bett_5 = 'Several days' then 1 when common_mental_health_symptoms_thoughts_that_you_would_be_bett_5 like '2 -%' or common_mental_health_symptoms_thoughts_that_you_would_be_bett_5 = 'More than half the days' then 2 when common_mental_health_symptoms_thoughts_that_you_would_be_bett_5 like '3 -%' or common_mental_health_symptoms_thoughts_that_you_would_be_bett_5 = 'Nearly every day' then 3 else null end, 0)) as total_score
    from {{ ref('qr_phq_9_s4') }}
    where subject_patient_id is not null
),

-- Combine all PHQ-9 sessions
all_phq9 as (
    select * from phq9_s1
    union all select * from phq9_s2
    union all select * from phq9_s3
    union all select * from phq9_s4
),

-- Get first and last scores per patient for PHQ-9
phq9_change as (
    select
        subject_patient_id,
        organization_id,
        min(case when session_number = 1 then total_score end) as first_score,
        max(session_number) as last_session,
        max(case when session_number = (select max(session_number) from all_phq9 a2 where a2.subject_patient_id = all_phq9.subject_patient_id) then total_score end) as last_score
    from all_phq9
    group by subject_patient_id, organization_id
    having count(distinct session_number) > 1
)

select
    subject_patient_id,
    organization_id,
    'PHQ-9' as assessment_type,
    first_score,
    last_session,
    last_score,
    first_score - last_score as score_improvement,
    case when first_score > 0 then round(((first_score - last_score)::numeric / first_score) * 100, 1) else 0 end as percent_improvement,
    last_score < first_score as improved,
    first_score >= 10 and last_score < 10 as achieved_remission
from phq9_change
where first_score is not null and last_score is not null
