{{
    config(
        materialized='view'
    )
}}

-- Anonymized view for qr_common_mental_health_symptoms
-- Automatically generated based on questionnaire_metadata.csv

select
    questionnaire_id as questionnaire_id,
    subject_patient_id as subject_patient_id,
    encounter_id as encounter_id,
    author_practitioner_id as author_practitioner_id,
    practitioner_location_id as practitioner_location_id,
    practitioner_organization_id as practitioner_organization_id,
    practitioner_id as practitioner_id,
    practitioner_careteam_id as practitioner_careteam_id,
    application_version as application_version,
    qr_id as qr_id,
    a_place_to_declare_values_that_cannot_be_created_using_fhirpath as a_place_to_declare_values_that_cannot_be_created_using_fhirpath,
    short_form_pcl_5_8_ipc_session_2_in_the_past_month_how_much_wer as short_form_pcl_5_8_ipc_session_2_in_the_past_month_how_much_wer,
    a_place_to_declare_values_that_cannot_be_created_using_fhirpa_2 as a_place_to_declare_values_that_cannot_be_created_using_fhirpa_2,
    short_form_pcl_5_8_ipc_session_2_in_the_past_month_how_much_w_2 as short_form_pcl_5_8_ipc_session_2_in_the_past_month_how_much_w_2,
    a_place_to_declare_values_that_cannot_be_created_using_fhirpa_3 as a_place_to_declare_values_that_cannot_be_created_using_fhirpa_3,
    short_form_pcl_5_8_ipc_session_2_in_the_past_month_how_much_w_3 as short_form_pcl_5_8_ipc_session_2_in_the_past_month_how_much_w_3,
    short_form_pcl_5_8_ipc_session_2_in_the_past_month_how_much_w_4 as short_form_pcl_5_8_ipc_session_2_in_the_past_month_how_much_w_4,
    short_form_pcl_5_8_ipc_session_2_in_the_past_month_how_much_w_5 as short_form_pcl_5_8_ipc_session_2_in_the_past_month_how_much_w_5,
    a_place_to_declare_values_that_cannot_be_created_using_fhirpa_4 as a_place_to_declare_values_that_cannot_be_created_using_fhirpa_4,
    phq_9_ipc_session_2_how_difficult_have_these_problems_made_it_f as phq_9_ipc_session_2_how_difficult_have_these_problems_made_it_f,
    a_place_to_declare_values_that_cannot_be_created_using_fhirpa_5 as a_place_to_declare_values_that_cannot_be_created_using_fhirpa_5,
    short_form_pcl_5_8_ipc_session_2_in_the_past_month_how_much_w_6 as short_form_pcl_5_8_ipc_session_2_in_the_past_month_how_much_w_6,
    a_place_to_declare_values_that_cannot_be_created_using_fhirpa_6 as a_place_to_declare_values_that_cannot_be_created_using_fhirpa_6,
    short_form_pcl_5_8_ipc_session_2_in_the_past_month_how_much_w_7 as short_form_pcl_5_8_ipc_session_2_in_the_past_month_how_much_w_7,
    short_form_pcl_5_8_ipc_session_2_in_the_past_month_how_much_w_8 as short_form_pcl_5_8_ipc_session_2_in_the_past_month_how_much_w_8,
    common_mental_health_symptoms_moving_or_speaking_so_slowly_that as common_mental_health_symptoms_moving_or_speaking_so_slowly_that,
    common_mental_health_symptoms_thoughts_that_you_would_be_better as common_mental_health_symptoms_thoughts_that_you_would_be_better,
    common_mental_health_symptoms_feeling_nervous_anxious_or_on_edg as common_mental_health_symptoms_feeling_nervous_anxious_or_on_edg,
    common_mental_health_symptoms_not_being_able_to_stop_or_control as common_mental_health_symptoms_not_being_able_to_stop_or_control,
    common_mental_health_symptoms_worrying_too_much_about_different as common_mental_health_symptoms_worrying_too_much_about_different,
    common_mental_health_symptoms_trouble_relaxing as common_mental_health_symptoms_trouble_relaxing,
    common_mental_health_symptoms_being_so_restless_that_it_s_hard_ as common_mental_health_symptoms_being_so_restless_that_it_s_hard_,
    common_mental_health_symptoms_becoming_easily_annoyed_or_irrita as common_mental_health_symptoms_becoming_easily_annoyed_or_irrita,
    common_mental_health_symptoms_feeling_afraid_as_if_something_aw as common_mental_health_symptoms_feeling_afraid_as_if_something_aw,
    common_mental_health_symptoms_little_interest_or_pleasure_in_do as common_mental_health_symptoms_little_interest_or_pleasure_in_do,
    common_mental_health_symptoms_feeling_down_depressed_or_hopeles as common_mental_health_symptoms_feeling_down_depressed_or_hopeles,
    common_mental_health_symptoms_trouble_falling_or_staying_asleep as common_mental_health_symptoms_trouble_falling_or_staying_asleep,
    common_mental_health_symptoms_feeling_tired_or_having_little_en as common_mental_health_symptoms_feeling_tired_or_having_little_en,
    common_mental_health_symptoms_poor_appetite_or_overeating as common_mental_health_symptoms_poor_appetite_or_overeating,
    common_mental_health_symptoms_feeling_bad_about_yourself_or_tha as common_mental_health_symptoms_feeling_bad_about_yourself_or_tha,
    common_mental_health_symptoms_trouble_concentrating_on_things_s as common_mental_health_symptoms_trouble_concentrating_on_things_s,
    'REDACTED' as patient_age,
    'REDACTED' as patient_date_of_birth,
    'REDACTED' as patient_name,
    a_place_to_declare_values_that_cannot_be_created_using_fhirpa_7 as a_place_to_declare_values_that_cannot_be_created_using_fhirpa_7,
    a_place_to_declare_values_that_cannot_be_created_using_fhirpa_8 as a_place_to_declare_values_that_cannot_be_created_using_fhirpa_8,
    CURRENT_TIMESTAMP as anonymized_at

from {{ ref('qr_common_mental_health_symptoms') }}