{{
    config(
        materialized='view'
    )
}}

-- Anonymized view for qr_gad_7_s1
-- Automatically generated based on questionnaire_metadata.csv

select
    questionnaire_id as questionnaire_id,
    subject_patient_id as subject_patient_id,
    encounter_id as encounter_id,
    author_practitioner_id as author_practitioner_id,
    practitioner_location_id as practitioner_location_id,
    practitioner_organization_id as practitioner_organization_id,
    practitioner_id as practitioner_id,
    practitioner_careteam_id as practitioner_careteam_id,
    application_version as application_version,
    qr_id as qr_id,
    a_place_to_declare_values_that_cannot_be_created_using_fhirpa_9 as a_place_to_declare_values_that_cannot_be_created_using_fhirpa_9,
    a_place_to_declare_values_that_cannot_be_created_using_fhirp_10 as a_place_to_declare_values_that_cannot_be_created_using_fhirp_10,
    a_place_to_declare_values_that_cannot_be_created_using_fhirp_11 as a_place_to_declare_values_that_cannot_be_created_using_fhirp_11,
    a_place_to_declare_values_that_cannot_be_created_using_fhirp_12 as a_place_to_declare_values_that_cannot_be_created_using_fhirp_12,
    add_family_member_registration_calculated_age_2 as add_family_member_registration_calculated_age_2,
    add_family_member_registration_calculated_month_2 as add_family_member_registration_calculated_month_2,
    add_family_member_registration_calculated_year_2 as add_family_member_registration_calculated_year_2,
    add_family_member_registration_date_of_birth_2 as add_family_member_registration_date_of_birth_2,
    a_place_to_declare_values_that_cannot_be_created_using_fhirp_13 as a_place_to_declare_values_that_cannot_be_created_using_fhirp_13,
    common_mental_health_symptoms_feeling_nervous_anxious_or_on_e_2 as common_mental_health_symptoms_feeling_nervous_anxious_or_on_e_2,
    common_mental_health_symptoms_not_being_able_to_stop_or_contr_2 as common_mental_health_symptoms_not_being_able_to_stop_or_contr_2,
    common_mental_health_symptoms_worrying_too_much_about_differe_2 as common_mental_health_symptoms_worrying_too_much_about_differe_2,
    common_mental_health_symptoms_trouble_relaxing_2 as common_mental_health_symptoms_trouble_relaxing_2,
    common_mental_health_symptoms_being_so_restless_that_it_s_har_2 as common_mental_health_symptoms_being_so_restless_that_it_s_har_2,
    common_mental_health_symptoms_becoming_easily_annoyed_or_irri_2 as common_mental_health_symptoms_becoming_easily_annoyed_or_irri_2,
    common_mental_health_symptoms_feeling_afraid_as_if_something__2 as common_mental_health_symptoms_feeling_afraid_as_if_something__2,
    a_place_to_declare_values_that_cannot_be_created_using_fhirp_14 as a_place_to_declare_values_that_cannot_be_created_using_fhirp_14,
    CURRENT_TIMESTAMP as anonymized_at

from {{ ref('qr_gad_7_s1') }}