{{
    config(
        materialized='view'
    )
}}

-- Anonymized view for qr_planning_next_steps with PII fields masked based on questionnaire_metadata.anon flag
-- Questionnaire: Planning Next Steps (Questionnaire/q-planning-next-steps)
-- PII fields masked: 3 fields

select 
    MD5(COALESCE(qr_id, '')::text) as qr_id_hash,
    questionnaire_id,
    MD5(COALESCE(subject_patient_id, '')::text) as subject_patient_id_hash,
    encounter_id,
    author_practitioner_id,
    practitioner_location_id,
    practitioner_organization_id,
    practitioner_id,
    practitioner_careteam_id,
    application_version,
        referral_to_mental_health_specialist,
        referred,
        okay,
        field_2cb66889,
        field_34a56c28,
        referres,
        field_34ab6c28,
        field_3b9f7e5d,
        sbirt_motivational_interviewing,
        safety,
        others,
        mental_health,
        not_interested,
        "20250924",
        field_69712544,
        field_76ba8dbe,
        hh,
        "20260505",
        field_9a8b7c6d,
        sbirt_motivational_interviewingbrspan_stylecolor006,
        field_ab12d39f,
        they_gtycyvuy,
        field_b2c3d4e5,
        test,
        field_bc2def4a,
        field_c3d4e5f6,
        field_c9d8b7a6,
        not_interested_28,
        field_cd34f5b1,
        iwbwb,
        needs_checkups,
        hhh,
        "20250827",
        referral_to_mental_health_specialist_34,
        already_received_a_similar_service,
        field_ef5617d3,
        peace,
        interested_but_not_now,
        supervisors_name,
        "d4e5f6a7-b8c9-4d0e-1f2a-3b4c5d6e7f8g",
        "e5f6a7b8-c9d0-4e1f-2a3b-4c5d6e7f8g9h",
        "f6a7b8c9-d0e1-4f2a-3b4c-5d6e7f8g9h0i",
        "financial-hardships-list",
        "is-fws",
        "is-ipc",
        "is-ipc-main",
        "is-ipc-optional",
        "is-mhs",
        "is-other-agency-services",
        "is-other-services-outside-agency",
        "is-sbirt",
        "is-sbirt-main",
        "is-sbirt-optional",
        "is-spi",
        'REDACTED' as "patient-age",
        'REDACTED' as "patient-dob",
        'REDACTED' as "patient-name",
        "scheduled-ipc-session-1-with-current-time",
        "scheduled-ipc-session-1-with-current-time-2",
        "task-id-000",
        "task-id-001",
        "task-id-002",
        "task-id-003",
        "task-id-004",
        "task-id-006",
        "task-id-planning-next-steps-pdf",
        CURRENT_TIMESTAMP as anonymized_at

from {{ ref('qr_planning_next_steps') }}