{{
    config(
        materialized='view'
    )
}}

-- Anonymized view for qr_planning_next_steps
-- Automatically generated based on questionnaire_metadata.csv

select 
    questionnaire_id as questionnaire_id,
    subject_patient_id as subject_patient_id,
    encounter_id as encounter_id,
    author_practitioner_id as author_practitioner_id,
    practitioner_location_id as practitioner_location_id,
    practitioner_organization_id as practitioner_organization_id,
    practitioner_id as practitioner_id,
    practitioner_careteam_id as practitioner_careteam_id,
    application_version as application_version,
    qr_id as qr_id,
    survey_response as survey_response,
    survey_response_2 as survey_response_2,
    survey_response_3 as survey_response_3,
    survey_response_4 as survey_response_4,
    survey_response_5 as survey_response_5,
    survey_response_6 as survey_response_6,
    survey_response_7 as survey_response_7,
    survey_response_8 as survey_response_8,
    survey_response_9 as survey_response_9,
    survey_response_10 as survey_response_10,
    survey_response_11 as survey_response_11,
    survey_response_12 as survey_response_12,
    survey_response_13 as survey_response_13,
    survey_response_14 as survey_response_14,
    survey_response_15 as survey_response_15,
    survey_response_16 as survey_response_16,
    survey_response_17 as survey_response_17,
    survey_response_18 as survey_response_18,
    survey_response_19 as survey_response_19,
    survey_response_20 as survey_response_20,
    survey_response_21 as survey_response_21,
    survey_response_22 as survey_response_22,
    survey_response_23 as survey_response_23,
    survey_response_24 as survey_response_24,
    survey_response_25 as survey_response_25,
    survey_response_26 as survey_response_26,
    survey_response_27 as survey_response_27,
    survey_response_28 as survey_response_28,
    survey_response_29 as survey_response_29,
    survey_response_30 as survey_response_30,
    survey_response_31 as survey_response_31,
    q_d4e5f6a7 as q_d4e5f6a7,
    survey_response_33 as survey_response_33,
    survey_response_34 as survey_response_34,
    q_e5f6a7b8 as q_e5f6a7b8,
    survey_response_36 as survey_response_36,
    survey_response_37 as survey_response_37,
    survey_response_38 as survey_response_38,
    survey_response_39 as survey_response_39,
    survey_response_40 as survey_response_40,
    q_f6a7b8c9 as q_f6a7b8c9,
    supervisor_recommendation_form as supervisor_recommendation_form,
    financial_hardships_list as financial_hardships_list,
    fws as fws,
    ipc as ipc,
    ipc_main as ipc_main,
    ipc_optional as ipc_optional,
    mhs as mhs,
    other_agency_services as other_agency_services,
    other_services_outside as other_services_outside,
    sbirt as sbirt,
    sbirt_main as sbirt_main,
    sbirt_optional as sbirt_optional,
    spi as spi,
    'REDACTED' as patient_age,
    'REDACTED' as patient_dob,
    'REDACTED' as patient_name,
    scheduled_ipc_session as scheduled_ipc_session,
    scheduled_ipc_session_59 as scheduled_ipc_session_59,
    task as task,
    task_61 as task_61,
    task_62 as task_62,
    task_63 as task_63,
    task_64 as task_64,
    task_65 as task_65,
    task_planning_next as task_planning_next,
    CURRENT_TIMESTAMP as anonymized_at

from {{ ref('qr_planning_next_steps') }}