{{
    config(
        materialized='view'
    )
}}

-- Anonymized view for qr_start_ipc_s1 with PII fields masked based on questionnaire_metadata.anon flag
-- Questionnaire: IPC Session 1 (Questionnaire/55)
-- PII fields masked: 9 fields

select 
    MD5(COALESCE(qr_id, '')::text) as qr_id_hash,
    questionnaire_id,
    MD5(COALESCE(subject_patient_id, '')::text) as subject_patient_id_hash,
    encounter_id,
    author_practitioner_id,
    practitioner_location_id,
    practitioner_organization_id,
    practitioner_id,
    practitioner_careteam_id,
    application_version,
        ipc_s1_patient_age,
        'REDACTED' as ipc_s1_patient_dob,
        ipc_s1_in_what_format_did_you_deliver_this_session_with_t,
        ipc_s1_in_the_past_6_months,
        ipc_s1_f1921,
        ipc_s1_in_the_past_1_year,
        ipc_s1_i_noticed_that_when_i_was_asking_about_important_p,
        'REDACTED' as ipc_s1_did_you_complete_the_required_assessments_and_the_,
        ipc_s1_do_you_think_an_important_persons_death_is_connect,
        'REDACTED' as ipc_s1_are_you_and_someone_else_having_a_strong_disagreem,
        ipc_s1_briefly_tell_me_about_the_disagreement,
        'REDACTED' as ipc_s1_how_has_this_disagreement_been_affecting_you,
        ipc_s1_have_there_been_any_changes_in_your_life_that_are_,
        ipc_s1_what_was_the_change,
        ipc_s1_when_did_this_happen,
        ipc_s1_if_the_client_did_not_mention_any_close_relationsh,
        ipc_s1_would_you_say_you_have_close_relationships,
        ipc_s1_has_anything_changed_in_your_life_so_that_now_you_,
        ipc_s1_f1882,
        ipc_s1_select_the_possible_interpersonal_problem_areas_yo,
        ipc_s1_your_most_distressing_current_symptoms_began,
        ipc_s1_taskid_session_1_navigator,
        ipc_s1_f1402,
        ipc_s1_when_did_this_event_happen,
        ipc_s1_is_there_anything_else_that_we_did_not_discuss_tha,
        ipc_s1_taskid_session_2_navigator,
        ipc_s1_on_a_scale_of_1_to_10_with_1_being_the_worst_mood_,
        ipc_s1_has_this_person_been_consistently_close_to_you_or_,
        ipc_s1_tell_me_about_your_relationship_with_this_person_h,
        ipc_s1_when_did_this_disagreement_happen,
        ipc_s1_do_you_want_to_propose_an_interpersonal_formulatio,
        ipc_s1_do_you_agree_with_this,
        ipc_s1_these_are_the_symptoms_you_said_you_are_currently_,
        ipc_s1_taskid_mood_pdf,
        ipc_s1_relationships_eg_talk_with_friends_or_vi,
        ipc_s1_is_there_anything_that_could_get_in_the_way_of_you,
        ipc_s1_f1813,
        ipc_s1_at_that_time_you_were_experiencing,
        ipc_s1_taskid_ipc_session_1_provider_pdf,
        ipc_s1_work_on_my_relationship_with_my_parents_,
        ipc_s1_f13931,
        ipc_s1_taskid_ipc_session_1_client_pdf,
        ipc_s1_of_these_symptoms_which_are_the_most_distressing,
        ipc_s1_f1814,
        ipc_s1_earlier_than_that_you_noticed_symptoms,
        ipc_s1_community_activities_eg_go_to_a_recreati,
        'REDACTED' as ipc_s1_patient_name,
        ipc_s1_f13932,
        ipc_s1_f1405,
        ipc_s1_when_did_these_symptoms_begin,
        ipc_s1_xxx,
        ipc_s1_yesterday_,
        ipc_s1_patient_gender,
        ipc_s1_has_this_person_been_consistently_close_to_you_or__54,
        ipc_s1_phq9_total,
        ipc_s1_possible_problem_areas,
        ipc_s1_at_that_time_you_were_experiencing_57,
        ipc_s1_gad7_total,
        ipc_s1_hobbies_eg_listen_to_music_play_video_ga,
        ipc_s1_what_was_going_on_in_your_life_when_you_started_to,
        ipc_s1_total_score,
        ipc_s1_ptsd_total,
        ipc_s1_zfgh,
        ipc_s1_how_has_this_relationship_changed_following_trauma,
        ipc_s1_do_you_agree_with_this_summary,
        ipc_s1_f1408,
        'REDACTED' as ipc_s1_observation_id_of_mood_rating_session_1_score,
        ipc_s1_what_about_before_that_was_there_a_time_before_in_,
        ipc_s1_religionspirituality_eg_pray_or_go_to_se,
        'REDACTED' as ipc_s1_mood_rating_total,
        ipc_s1_person_1_is,
        ipc_s1_has_this_person_been_consistently_close_to_you_or__72,
        ipc_s1_phq9_total_meaning,
        ipc_s1_what_were_the_symptoms,
        ipc_s1_with_my_pastor_,
        ipc_s1_gad7_total_meaning,
        ipc_s1_f13941,
        ipc_s1_ptsd_total_meaning_toggle,
        ipc_s1_when_did_you_notice_these_symptoms,
        ipc_s1_other,
        'REDACTED' as ipc_s1_mood_rating_comment,
        ipc_s1_f1384,
        ipc_s1_f13942,
        ipc_s1_f14011,
        ipc_s1_what_was_happening_then,
        ipc_s1_encounter_id_of_ipc_session_1,
        ipc_s1_has_this_person_been_consistently_close_to_you_or__87,
        ipc_s1_ex,
        ipc_s1_how_has_this_relationship_changed_following_trauma_89,
        ipc_s1_person_2_is,
        ipc_s1_f13951,
        ipc_s1_f13952,
        ipc_s1_gud,
        ipc_s1_how_has_this_relationship_changed_following_trauma_94,
        ipc_s1_person_3_is,
        ipc_s1_f13961,
        ipc_s1_f13962,
        ipc_s1_how_has_this_relationship_changed_following_trauma_98,
        ipc_s1_person_4_is,
        'REDACTED' as date_of_birth,
        age,
        birth_month,
        age_years,
        encounter_reference,
        seeing_someone_be_killed_or_seriously_injured,
        "f1.38.3",
        "f1.46.2",
        "task-id-008",
        "task-id-009",
        "task-id-010",
        "task-id-012",
        CURRENT_TIMESTAMP as anonymized_at

from {{ ref('qr_start_ipc_s1') }}