{{
    config(
        materialized='view'
    )
}}

-- Anonymized view for qr_start_ipc_s4
-- Automatically generated based on questionnaire_metadata.csv

select
    questionnaire_id as questionnaire_id,
    subject_patient_id as subject_patient_id,
    encounter_id as encounter_id,
    author_practitioner_id as author_practitioner_id,
    practitioner_location_id as practitioner_location_id,
    practitioner_organization_id as practitioner_organization_id,
    practitioner_id as practitioner_id,
    practitioner_careteam_id as practitioner_careteam_id,
    application_version as application_version,
    qr_id as qr_id,
    ipc_session_4_after_today_s_session_i_will_be_referring_you_for as ipc_session_4_after_today_s_session_i_will_be_referring_you_for,
    ipc_session_4_do_you_remember_why_you_came_let_s_talk_about_how as ipc_session_4_do_you_remember_why_you_came_let_s_talk_about_how,
    ipc_session_4_what_do_you_think_are_some_situations_that_may_tr as ipc_session_4_what_do_you_think_are_some_situations_that_may_tr,
    ipc_session_4_what_do_you_think_are_some_situations_that_may__2 as ipc_session_4_what_do_you_think_are_some_situations_that_may__2,
    ipc_session_4_i_am_going_to_provide_you_with_our_agency_s_conta as ipc_session_4_i_am_going_to_provide_you_with_our_agency_s_conta,
    discussion_with_supervisor_for_severe_mental_health_did_you_d_2 as discussion_with_supervisor_for_severe_mental_health_did_you_d_2,
    a_place_to_declare_values_that_cannot_be_created_using_fhir_118 as a_place_to_declare_values_that_cannot_be_created_using_fhir_118,
    ipc_session_4_how_does_it_make_you_feel_to_know_that_today_is_o as ipc_session_4_how_does_it_make_you_feel_to_know_that_today_is_o,
    discussion_with_supervisor_for_severe_mental_health_what_is_t_2 as discussion_with_supervisor_for_severe_mental_health_what_is_t_2,
    survey_response_13 as survey_response_13,
    ipc_session_4_let_s_talk_about_what_skills_you_learned_here_tha as ipc_session_4_let_s_talk_about_what_skills_you_learned_here_tha,
    ipc_session_4_let_s_talk_about_what_skills_you_learned_here_t_2 as ipc_session_4_let_s_talk_about_what_skills_you_learned_here_t_2,
    ipc_session_4_let_s_look_at_your_symptom_changes_what_were_your as ipc_session_4_let_s_look_at_your_symptom_changes_what_were_your,
    mood_rating_ipc_session_4 as mood_rating_ipc_session_4,
    ipc_session_4_how_do_you_feel_about_today_being_our_last_sessio as ipc_session_4_how_do_you_feel_about_today_being_our_last_sessio,
    discussion_with_supervisor_for_severe_mental_health_referral__2 as discussion_with_supervisor_for_severe_mental_health_referral__2,
    ipc_session_4_in_what_format_did_you_deliver_this_session_with_ as ipc_session_4_in_what_format_did_you_deliver_this_session_with_,
    ipc_session_4_how_would_you_know_if_your_symptoms_are_coming_ba as ipc_session_4_how_would_you_know_if_your_symptoms_are_coming_ba,
    ipc_session_4_after_today_s_session_i_can_refer_you_for_clinica as ipc_session_4_after_today_s_session_i_can_refer_you_for_clinica,
    ipc_session_4_reason as ipc_session_4_reason,
    ipc_session_4_what_are_some_of_the_skills_you_learned_here_that as ipc_session_4_what_are_some_of_the_skills_you_learned_here_that,
    a_place_to_declare_values_that_cannot_be_created_using_fhir_119 as a_place_to_declare_values_that_cannot_be_created_using_fhir_119,
    a_place_to_declare_values_that_cannot_be_created_using_fhir_120 as a_place_to_declare_values_that_cannot_be_created_using_fhir_120,
    ipc_session_4_please_select_how_you_would_like_to_proceed_with_ as ipc_session_4_please_select_how_you_would_like_to_proceed_with_,
    ipc_session_4_what_do_you_think_you_still_need_to_work_on_regar as ipc_session_4_what_do_you_think_you_still_need_to_work_on_regar,
    ipc_session_4_what_we_know_is_that_symptoms_can_come_back_in_th as ipc_session_4_what_we_know_is_that_symptoms_can_come_back_in_th,
    ipc_session_4_what_do_you_think_you_still_need_to_work_on_reg_2 as ipc_session_4_what_do_you_think_you_still_need_to_work_on_reg_2,
    ipc_session_2_did_you_complete_the_required_assessment_s_and__4 as ipc_session_2_did_you_complete_the_required_assessment_s_and__4,
    survey_response_14 as survey_response_14,
    ipc_session_4_total_score as ipc_session_4_total_score,
    ipc_session_4_what_are_some_of_the_skills_you_learned_here_th_2 as ipc_session_4_what_are_some_of_the_skills_you_learned_here_th_2,
    ipc_session_4_let_s_look_at_your_symptom_changes_what_were_yo_2 as ipc_session_4_let_s_look_at_your_symptom_changes_what_were_yo_2,
    a_place_to_declare_values_that_cannot_be_created_using_fhir_121 as a_place_to_declare_values_that_cannot_be_created_using_fhir_121,
    ipc_session_4_do_you_remember_why_you_came_let_s_talk_about_h_2 as ipc_session_4_do_you_remember_why_you_came_let_s_talk_about_h_2,
    survey_response_15 as survey_response_15,
    ipc_session_4_phq_9_total as ipc_session_4_phq_9_total,
    ipc_session_4_gad_7_total as ipc_session_4_gad_7_total,
    ipc_session_4_ptsd_total as ipc_session_4_ptsd_total,
    mood_rating_ipc_session_2_on_a_scale_of_1_to_10_with_1_being__8 as mood_rating_ipc_session_2_on_a_scale_of_1_to_10_with_1_being__8,
    discussion_with_supervisor_for_severe_mental_health_superviso_3 as discussion_with_supervisor_for_severe_mental_health_superviso_3,
    ipc_session_4_details as ipc_session_4_details,
    ipc_session_4_is_the_client_connected_to_clinical_care as ipc_session_4_is_the_client_connected_to_clinical_care,
    CURRENT_TIMESTAMP as anonymized_at

from {{ ref('qr_start_ipc_s4') }}