{{
    config(
        materialized='view'
    )
}}

-- Anonymized view for qr_start_ipc_s3
-- Automatically generated based on questionnaire_metadata.csv

select 
    questionnaire_id as questionnaire_id,
    subject_patient_id as subject_patient_id,
    encounter_id as encounter_id,
    author_practitioner_id as author_practitioner_id,
    practitioner_location_id as practitioner_location_id,
    practitioner_organization_id as practitioner_organization_id,
    practitioner_id as practitioner_id,
    practitioner_careteam_id as practitioner_careteam_id,
    application_version as application_version,
    qr_id as qr_id,
    decision_analysis_example as decision_analysis_example,
    phq_total_meaning as phq_total_meaning,
    interpersonal_skills_building as interpersonal_skills_building,
    gad_total_meaning as gad_total_meaning,
    role_play_example as role_play_example,
    renegotiation as renegotiation,
    communication_analysis_example as communication_analysis_example,
    explore_problem_questions as explore_problem_questions,
    identified_stage_disagreement as identified_stage_disagreement,
    role_play_example_10 as role_play_example_10,
    mood_rating_ipc as mood_rating_ipc,
    impasse_questions_asked as impasse_questions_asked,
    feelings_change_questions as feelings_change_questions,
    explore_new_relationships as explore_new_relationships,
    decision_analysis as decision_analysis,
    role_play_example_16 as role_play_example_16,
    place_declare_values as place_declare_values,
    work_home_example as work_home_example,
    discuss_relationship as discuss_relationship,
    assess_violence as assess_violence,
    ipc_session as ipc_session,
    survey_response as survey_response,
    decision_analysis_23 as decision_analysis_23,
    ipc_session_24 as ipc_session_24,
    communication_analysis_example_25 as communication_analysis_example_25,
    role_play_example_26 as role_play_example_26,
    mood_rating_ipc_27 as mood_rating_ipc_27,
    communication_analysis_example_28 as communication_analysis_example_28,
    work_home_example_29 as work_home_example_29,
    old_role_questions as old_role_questions,
    discuss_close_relationships as discuss_close_relationships,
    you_prefer_focus as you_prefer_focus,
    disagreements as disagreements,
    new_role_questions as new_role_questions,
    discuss_relationship_questions as discuss_relationship_questions,
    communication_analysis_example_36 as communication_analysis_example_36,
    renegotiation_questions_asked as renegotiation_questions_asked,
    explore_problem as explore_problem,
    ipc_session_39 as ipc_session_39,
    assess_violence_you as assess_violence_you,
    survey_response_41 as survey_response_41,
    decision_analysis_example_42 as decision_analysis_example_42,
    new_role as new_role,
    increase_activities_others as increase_activities_others,
    work_home_example_45 as work_home_example_45,
    explore_new_relationships_46 as explore_new_relationships_46,
    explore_difficulties_relations as explore_difficulties_relations,
    decision_analysis_example_48 as decision_analysis_example_48,
    discuss_work_home as discuss_work_home,
    interventions_tab_select as interventions_tab_select,
    explore_difficulties_relations_51 as explore_difficulties_relations_51,
    old_role as old_role,
    disagreements_questions_asked as disagreements_questions_asked,
    decision_analysis_example_54 as decision_analysis_example_54,
    place_declare_values_55 as place_declare_values_55,
    place_declare_values_56 as place_declare_values_56,
    place_declare_values_57 as place_declare_values_57,
    guiding_prompts_stages as guiding_prompts_stages,
    dissolution_questions_asked as dissolution_questions_asked,
    format_you_deliver as format_you_deliver,
    impasse as impasse,
    interpersonal_skills_building_62 as interpersonal_skills_building_62,
    you_complete_required as you_complete_required,
    add_family_member as add_family_member,
    assess_violence_anything as assess_violence_anything,
    discuss_death_questions as discuss_death_questions,
    decision_analysis_67 as decision_analysis_67,
    increase_activities_others_68 as increase_activities_others_68,
    ipc_session_69 as ipc_session_69,
    add_family_member_70 as add_family_member_70,
    add_family_member_71 as add_family_member_71,
    add_family_member_72 as add_family_member_72,
    phq_total as phq_total,
    gad_total as gad_total,
    ptsd_total as ptsd_total,
    ptsd_total_meaning as ptsd_total_meaning,
    identified_stage_disagreement_77 as identified_stage_disagreement_77,
    discuss_close_relationships_78 as discuss_close_relationships_78,
    dissolution as dissolution,
    interpersonal_skills_building_80 as interpersonal_skills_building_80,
    place_declare_values_81 as place_declare_values_81,
    decision_analysis_82 as decision_analysis_82,
    discuss_death as discuss_death,
    work_home_example_84 as work_home_example_84,
    identify_social_settings as identify_social_settings,
    interpersonal_skills_building_86 as interpersonal_skills_building_86,
    place_declare_values_87 as place_declare_values_87,
    mood_rating_ipc_88 as mood_rating_ipc_88,
    guiding_prompts_disagreements as guiding_prompts_disagreements,
    feelings_change as feelings_change,
    place_declare_values_91 as place_declare_values_91,
    task as task,
    task_93 as task_93,
    task_94 as task_94,
    task_95 as task_95,
    task_96 as task_96,
    task_97 as task_97,
    CURRENT_TIMESTAMP as anonymized_at

from {{ ref('qr_start_ipc_s3') }}